import Mathlib.Data.Rat.Defs

/-!
# Frozen trained XOR parameters

Generated by `scripts/export_checkpoint.py`; do not edit by hand.
Source: seed 7, 1000 Adam steps, TorchLean native binary32, typed graph, CPU.
Tensor order: W1 [4,2], b1 [4], W2 [2,4], b2 [2], flattened row-major.
The binary64 checkpoint words contain exact widened binary32 values.
-/

namespace NeuralSpec.Xor.Checkpoint

def sha256 : String := "5b2c2f4adf6f09626e0c1de16bb256b62b9c92b9d653c2b6c565e5954a1c4536"

/-- Raw binary64 payloads from the identified checkpoint, in tensor order. -/
def sourceBits : List Nat :=
  [4604485888007733248,
   13833883401590931456,
   13826653106005344256,
   13829313141386772480,
   13830705114517602304,
   4604122835495944192,
   13823007499109793792,
   13820840487319240704,
   4604367076864294912,
   4604299443477413888,
   4597500561250582528,
   0,
   13830324812343410688,
   4609601081314377728,
   13832044185462505472,
   4603981932651347968,
   4606954387175112704,
   13832973066092675072,
   4608672098678734848,
   4599615726343421952,
   4607044779593695232,
   4579943431802978304]

/-- Exact binary32 interchange words for native and FloatLib execution. -/
def sourceBits32 : List UInt32 :=
  [1060330536,
   3219037509,
   3205570034,
   3210524736,
   3213117488,
   1059654298,
   3198779562,
   3194743188,
   1060109233,
   1059983256,
   1047319351,
   0,
   3212409120,
   1069858326,
   3215611702,
   1059391846,
   1064928474,
   3217341877,
   1068127961,
   1051259153,
   1065096843,
   1014616649]

def w1_00 : ℚ := 1469317 / 2097152
def w1_01 : ℚ := -14589253 / 8388608
def w1_10 : ℚ := -4755193 / 8388608
def w1_11 : ℚ := -226017 / 262144
def w1_20 : ℚ := -541827 / 524288
def w1_21 : ℚ := 5539149 / 8388608
def w1_30 : ℚ := -5554261 / 16777216
def w1_31 : ℚ := -3865189 / 16777216
def b1_0 : ℚ := 11533233 / 16777216
def b1_1 : ℚ := 1425907 / 2097152
def b1_2 : ℚ := 15520567 / 67108864
def b1_3 : ℚ := 0 / 1
def w2_00 : ℚ := -510921 / 524288
def w2_01 : ℚ := 6446859 / 4194304
def w2_02 : ℚ := -5581723 / 4194304
def w2_03 : ℚ := 5407923 / 8388608
def w2_10 : ℚ := 8176237 / 8388608
def w2_11 : ℚ := -12893621 / 8388608
def w2_12 : ℚ := 11163353 / 8388608
def w2_13 : ℚ := 11071761 / 33554432
def b2_0 : ℚ := 16520843 / 16777216
def b2_1 : ℚ := 16372297 / 1073741824

/-- All 22 coefficients used by the exact-real network, in checkpoint order. -/
def parameters : List ℚ :=
  [w1_00, w1_01, w1_10, w1_11, w1_20, w1_21, w1_30, w1_31, b1_0, b1_1, b1_2, b1_3, w2_00, w2_01, w2_02, w2_03, w2_10, w2_11, w2_12, w2_13, b2_0, b2_1]

end NeuralSpec.Xor.Checkpoint
