#!/usr/bin/env python3
"""Export the frozen XOR checkpoint as exact Lean rationals, or check the export."""

import argparse
from fractions import Fraction
import hashlib
import json
from pathlib import Path
import struct
import sys


EXPECTED_SHA256 = "5b2c2f4adf6f09626e0c1de16bb256b62b9c92b9d653c2b6c565e5954a1c4536"
SHAPES = [[4, 2], [4], [2, 4], [2]]
NAMES = (
    [f"w1_{i}{j}" for i in range(4) for j in range(2)]
    + [f"b1_{i}" for i in range(4)]
    + [f"w2_{i}{j}" for i in range(2) for j in range(4)]
    + [f"b2_{i}" for i in range(2)]
)


def decode_finite_binary64(bits):
    """Decode with integer arithmetic, independently of native floating-point math."""
    if type(bits) is not int or not 0 <= bits < 2**64:
        raise ValueError("Expected an unsigned 64-bit integer payload")
    exponent = (bits >> 52) & 0x7FF
    fraction = bits & (2**52 - 1)
    if exponent == 0x7FF:
        raise ValueError("NaN and infinity are not exact-real parameters")
    significand = fraction if exponent == 0 else 2**52 + fraction
    shift = -1074 if exponent == 0 else exponent - 1075
    magnitude = Fraction(significand) * Fraction(2) ** shift
    return -magnitude if bits >> 63 else magnitude


def render(checkpoint):
    raw = checkpoint.read_bytes()
    if hashlib.sha256(raw).hexdigest() != EXPECTED_SHA256:
        raise ValueError("Checkpoint identity mismatch: this proof targets the frozen seed-7 run")
    document = json.loads(raw)
    if document.get("format") != "torchlean_state_bits_v1":
        raise ValueError("Unsupported checkpoint format")
    tensors = document["state"]
    if len(tensors) != len(SHAPES):
        raise ValueError("Expected four parameter tensors")
    words = []
    for tensor, shape in zip(tensors, SHAPES):
        if tensor["shape"] != shape:
            raise ValueError(f"Unexpected tensor shape: {tensor['shape']}")
        count = 1
        for dimension in shape:
            count *= dimension
        if len(tensor["values"]) != count:
            raise ValueError("Parameter payload length does not match its shape")
        words.extend(tensor["values"])
    values = [decode_finite_binary64(word) for word in words]
    # Independently check decoding, and that each payload is an exact binary32 value.
    words32 = []
    for word, value in zip(words, values):
        native = struct.unpack(">d", word.to_bytes(8, "big"))[0]
        if Fraction(native) != value:
            raise ValueError("Integer and native binary64 decoders disagree")
        binary32 = struct.unpack(">f", struct.pack(">f", native))[0]
        words32.append(int.from_bytes(struct.pack(">f", native), "big"))
        if Fraction(binary32) != value:
            raise ValueError("The native binary32 training path cannot produce this parameter")
    lines = [
        "import Mathlib.Data.Rat.Defs",
        "",
        "/-!",
        "# Frozen trained XOR parameters",
        "",
        "Generated by `scripts/export_checkpoint.py`; do not edit by hand.",
        "Source: seed 7, 1000 Adam steps, TorchLean native binary32, typed graph, CPU.",
        "Tensor order: W1 [4,2], b1 [4], W2 [2,4], b2 [2], flattened row-major.",
        "The binary64 checkpoint words contain exact widened binary32 values.",
        "-/",
        "",
        "namespace NeuralSpec.Xor.Checkpoint",
        "",
        f'def sha256 : String := "{EXPECTED_SHA256}"',
        "",
        "/-- Raw binary64 payloads from the identified checkpoint, in tensor order. -/",
        "def sourceBits : List Nat :=",
        "  [" + ",\n   ".join(map(str, words)) + "]",
        "",
    ]
    lines += [
        "/-- Exact binary32 interchange words for native and FloatLib execution. -/",
        "def sourceBits32 : List UInt32 :=",
        "  [" + ",\n   ".join(map(str, words32)) + "]",
        "",
    ]
    for name, value in zip(NAMES, values):
        lines.append(f"def {name} : ℚ := {value.numerator} / {value.denominator}")
    lines += [
        "",
        "/-- All 22 coefficients used by the exact-real network, in checkpoint order. -/",
        "def parameters : List ℚ :=",
        "  [" + ", ".join(NAMES) + "]",
        "",
        "end NeuralSpec.Xor.Checkpoint",
        "",
    ]
    return "\n".join(lines)


def main():
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("checkpoint", type=Path, nargs="?", default=root / "artifacts/xor.state")
    parser.add_argument("--output", type=Path, default=root / "NeuralSpec/Network/Xor/Parameters.lean")
    parser.add_argument("--check", action="store_true", help="Compare without writing files")
    args = parser.parse_args()
    try:
        generated = render(args.checkpoint)
        if args.check:
            if args.output.read_text() != generated:
                raise ValueError("The Lean parameter export differs from the frozen checkpoint")
            print("All 22 exact parameters, tensor layouts, source bits, and checkpoint SHA-256 match.")
        else:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(generated)
            print(f"Exported 22 exact parameters to {args.output}")
    except (ValueError, KeyError, TypeError, OSError, OverflowError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
